package GUI;

import Model.Lifeline;
import Model.CallAFriend;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

public class CallAFriendFrame extends javax.swing.JFrame {

    private static Lifeline l;

    /**
     * Creates new form CallAFriendFrame
     */
    public CallAFriendFrame(Lifeline c) {
        this.l = c;
        this.setContentPane(new JLabel(new ImageIcon("src/Image/Background.png")));
        initComponents();
        
        this.sayingLabel.setText(((CallAFriend) c).getSaying());

        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        friendLabel = new javax.swing.JLabel();
        sayingLabel = new javax.swing.JLabel();
        ContinueLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Call a Friend");
        setPreferredSize(new java.awt.Dimension(400, 300));

        friendLabel.setForeground(new java.awt.Color(255, 255, 255));
        friendLabel.setText("Your friend says:");

        sayingLabel.setForeground(new java.awt.Color(255, 255, 255));

        ContinueLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Continue.png"))); // NOI18N
        ContinueLabel.setText("Continue game");
        ContinueLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ContinueLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ContinueLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ContinueLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ContinueLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(200, Short.MAX_VALUE)
                .addComponent(ContinueLabel)
                .addGap(50, 50, 50))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(friendLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sayingLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(30, 30, 30))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addComponent(friendLabel)
                .addGap(18, 18, 18)
                .addComponent(sayingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ContinueLabel)
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ContinueLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ContinueLabelMouseClicked
        this.dispose();
    }//GEN-LAST:event_ContinueLabelMouseClicked

    private void ContinueLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ContinueLabelMouseEntered
        this.ContinueLabel.setIcon(new ImageIcon("src/Image/Continue2.png"));
    }//GEN-LAST:event_ContinueLabelMouseEntered

    private void ContinueLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ContinueLabelMouseExited
        this.ContinueLabel.setIcon(new ImageIcon("src/Image/Continue.png"));
    }//GEN-LAST:event_ContinueLabelMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CallAFriendFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CallAFriendFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CallAFriendFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CallAFriendFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CallAFriendFrame(l).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ContinueLabel;
    private javax.swing.JLabel friendLabel;
    private javax.swing.JLabel sayingLabel;
    // End of variables declaration//GEN-END:variables
}
