package GUI;

import javax.swing.ImageIcon;
import javax.swing.JLabel;

public class MenuFrame extends javax.swing.JFrame {

    /**
     * Creates new form MenuFrame
     */
    public MenuFrame() {
        this.setContentPane(new JLabel(new ImageIcon("src/Image/Background.png")));
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        playLabel = new javax.swing.JLabel();
        exitLabel = new javax.swing.JLabel();
        logoLabel = new javax.swing.JLabel();
        ruleLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Who Wants to Be a Milionaire");
        setPreferredSize(new java.awt.Dimension(650, 550));

        playLabel.setForeground(new java.awt.Color(255, 255, 255));
        playLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Blue.png"))); // NOI18N
        playLabel.setText("Play");
        playLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        playLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                playLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                playLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                playLabelMouseExited(evt);
            }
        });

        exitLabel.setForeground(new java.awt.Color(255, 255, 255));
        exitLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Blue.png"))); // NOI18N
        exitLabel.setText("Exit");
        exitLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        exitLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitLabelMouseExited(evt);
            }
        });

        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Logo.png"))); // NOI18N

        ruleLabel.setForeground(new java.awt.Color(255, 255, 255));
        ruleLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Blue.png"))); // NOI18N
        ruleLabel.setText("Game Rule");
        ruleLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ruleLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ruleLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ruleLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ruleLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ruleLabel)
                    .addComponent(exitLabel)
                    .addComponent(playLabel))
                .addContainerGap(143, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(152, Short.MAX_VALUE)
                .addComponent(logoLabel)
                .addGap(200, 200, 200))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(logoLabel)
                .addGap(30, 30, 30)
                .addComponent(playLabel)
                .addGap(30, 30, 30)
                .addComponent(ruleLabel)
                .addGap(30, 30, 30)
                .addComponent(exitLabel)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void playLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playLabelMouseClicked
        this.dispose();
        new PlayerFrame().setVisible(true);
    }//GEN-LAST:event_playLabelMouseClicked

    private void playLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playLabelMouseEntered
        this.playLabel.setIcon(new ImageIcon("src/Image/Blue2.png"));
    }//GEN-LAST:event_playLabelMouseEntered

    private void playLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playLabelMouseExited
        this.playLabel.setIcon(new ImageIcon("src/Image/Blue.png"));
    }//GEN-LAST:event_playLabelMouseExited

    private void exitLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitLabelMouseClicked

    private void exitLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseEntered
        this.exitLabel.setIcon(new ImageIcon("src/Image/Blue2.png"));
    }//GEN-LAST:event_exitLabelMouseEntered

    private void exitLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseExited
        this.exitLabel.setIcon(new ImageIcon("src/Image/Blue.png"));
    }//GEN-LAST:event_exitLabelMouseExited

    private void ruleLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ruleLabelMouseClicked
        new RuleFrame().setVisible(true);
    }//GEN-LAST:event_ruleLabelMouseClicked

    private void ruleLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ruleLabelMouseEntered
        this.ruleLabel.setIcon(new ImageIcon("src/Image/Blue2.png"));
    }//GEN-LAST:event_ruleLabelMouseEntered

    private void ruleLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ruleLabelMouseExited
        this.ruleLabel.setIcon(new ImageIcon("src/Image/Blue.png"));
    }//GEN-LAST:event_ruleLabelMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel exitLabel;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JLabel playLabel;
    private javax.swing.JLabel ruleLabel;
    // End of variables declaration//GEN-END:variables
}
