package GUI;

import Model.Player;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

public class RestartFrame extends javax.swing.JFrame {

    private static Player player;
    
    /**
     * Creates new form RestartFrame
     */
    public RestartFrame(Player player) {
        this.player = player;
        this.setContentPane(new JLabel(new ImageIcon("src/Image/Background.png")));
        initComponents();

        this.prizeLabel.setText("$" + Integer.toString(player.getWinning()));
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        askLabel = new javax.swing.JLabel();
        restartLabel = new javax.swing.JLabel();
        quitLabel = new javax.swing.JLabel();
        prizeLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Restart the game");
        setPreferredSize(new java.awt.Dimension(500, 400));

        askLabel.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        askLabel.setForeground(new java.awt.Color(255, 255, 255));
        askLabel.setText("Do you want to restart the game?");

        restartLabel.setForeground(new java.awt.Color(255, 255, 255));
        restartLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Green.png"))); // NOI18N
        restartLabel.setText("Restart");
        restartLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        restartLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                restartLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                restartLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                restartLabelMouseExited(evt);
            }
        });

        quitLabel.setForeground(new java.awt.Color(255, 255, 255));
        quitLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Red.png"))); // NOI18N
        quitLabel.setText("Quit");
        quitLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        quitLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quitLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                quitLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                quitLabelMouseExited(evt);
            }
        });

        prizeLabel.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        prizeLabel.setForeground(new java.awt.Color(255, 255, 0));
        prizeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/totalprize.png"))); // NOI18N
        prizeLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 2, Short.MAX_VALUE)
                        .addComponent(prizeLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(quitLabel)
                                    .addComponent(restartLabel)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(askLabel)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(prizeLabel)
                .addGap(45, 45, 45)
                .addComponent(askLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(restartLabel)
                .addGap(18, 18, 18)
                .addComponent(quitLabel)
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void restartLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_restartLabelMouseClicked
        this.dispose();
        new PlayerFrame().setVisible(true);
    }//GEN-LAST:event_restartLabelMouseClicked

    private void restartLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_restartLabelMouseEntered
        this.restartLabel.setIcon(new ImageIcon("src/Image/Green2.png"));
    }//GEN-LAST:event_restartLabelMouseEntered

    private void restartLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_restartLabelMouseExited
        this.restartLabel.setIcon(new ImageIcon("src/Image/Green.png"));
    }//GEN-LAST:event_restartLabelMouseExited

    private void quitLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quitLabelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_quitLabelMouseClicked

    private void quitLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quitLabelMouseEntered
        this.quitLabel.setIcon(new ImageIcon("src/Image/Red2.png"));
    }//GEN-LAST:event_quitLabelMouseEntered

    private void quitLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quitLabelMouseExited
        this.quitLabel.setIcon(new ImageIcon("src/Image/Red.png"));
    }//GEN-LAST:event_quitLabelMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RestartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RestartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RestartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RestartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RestartFrame(player).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel askLabel;
    private javax.swing.JLabel prizeLabel;
    private javax.swing.JLabel quitLabel;
    private javax.swing.JLabel restartLabel;
    // End of variables declaration//GEN-END:variables
}
